sudo: required
dist: trusty
language: c++

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libsfml-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sfml; fi

script: 
  - cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .
  - make
  
