sudo: required
dist: precise
language: c++

matrix:
  include:
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-5
#      env: COMPILER=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake
      env: COMPILER=g++-6
#    - compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise-3.7
#          packages:
#            - clang-3.7
#      env: COMPILER=clang++-3.7

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libsfml-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sfml; fi

script: 
  - cmake --version
  - cmake .
  - make
  
