sudo: required
dist: trusty
language: c++

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - libpthread-stubs0-dev
            - libgl1-mesa-dev
            - libx11-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libglew-dev
            - libjpeg-dev
            - libsndfile1-dev
            - libopenal-dev
            - libudev-dev
            - g++-5
      env: COMPILER=g++-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - libpthread-stubs0-dev
            - libgl1-mesa-dev
            - libx11-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libglew-dev
            - libjpeg-dev
            - libsndfile1-dev
            - libopenal-dev
            - libudev-dev
            - g++-6
      env: COMPILER=g++-6

before_install:
  - git clone https://github.com/SFML/SFML.git
  - cd SFML
  - mkdir install
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
  - make
  - make install
  - cd ../../

script: 
  - cmake --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DSFML_ROOT=./SFML/install -DCMAKE_MODULE_PATH=./SFML/cmake/Modules .
  - make
  
