# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Source\SenBoy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Source\SenBoy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Source\SenBoy\CMakeFiles D:\Source\SenBoy\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Source\SenBoy\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SenBoy

# Build rule for target.
SenBoy: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 SenBoy
.PHONY : SenBoy

# fast build rule for target.
SenBoy/fast:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/build
.PHONY : SenBoy/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles\run.dir\build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/GPU.obj: src/GPU.cpp.obj
.PHONY : src/GPU.obj

# target to build an object file
src/GPU.cpp.obj:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/GPU.cpp.obj
.PHONY : src/GPU.cpp.obj

src/GPU.i: src/GPU.cpp.i
.PHONY : src/GPU.i

# target to preprocess a source file
src/GPU.cpp.i:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/GPU.cpp.i
.PHONY : src/GPU.cpp.i

src/GPU.s: src/GPU.cpp.s
.PHONY : src/GPU.s

# target to generate assembly for a file
src/GPU.cpp.s:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/GPU.cpp.s
.PHONY : src/GPU.cpp.s

src/MMU.obj: src/MMU.cpp.obj
.PHONY : src/MMU.obj

# target to build an object file
src/MMU.cpp.obj:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/MMU.cpp.obj
.PHONY : src/MMU.cpp.obj

src/MMU.i: src/MMU.cpp.i
.PHONY : src/MMU.i

# target to preprocess a source file
src/MMU.cpp.i:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/MMU.cpp.i
.PHONY : src/MMU.cpp.i

src/MMU.s: src/MMU.cpp.s
.PHONY : src/MMU.s

# target to generate assembly for a file
src/MMU.cpp.s:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/MMU.cpp.s
.PHONY : src/MMU.cpp.s

src/Z80.obj: src/Z80.cpp.obj
.PHONY : src/Z80.obj

# target to build an object file
src/Z80.cpp.obj:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/Z80.cpp.obj
.PHONY : src/Z80.cpp.obj

src/Z80.i: src/Z80.cpp.i
.PHONY : src/Z80.i

# target to preprocess a source file
src/Z80.cpp.i:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/Z80.cpp.i
.PHONY : src/Z80.cpp.i

src/Z80.s: src/Z80.cpp.s
.PHONY : src/Z80.s

# target to generate assembly for a file
src/Z80.cpp.s:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/Z80.cpp.s
.PHONY : src/Z80.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles\SenBoy.dir\build.make CMakeFiles/SenBoy.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... install/local
	@echo ... install/strip
	@echo ... edit_cache
	@echo ... install
	@echo ... rebuild_cache
	@echo ... SenBoy
	@echo ... run
	@echo ... list_install_components
	@echo ... src/GPU.obj
	@echo ... src/GPU.i
	@echo ... src/GPU.s
	@echo ... src/MMU.obj
	@echo ... src/MMU.i
	@echo ... src/MMU.s
	@echo ... src/Z80.obj
	@echo ... src/Z80.i
	@echo ... src/Z80.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

